[project]
name = "prisoners-benchmark"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "altair<5.5",
    "marimo",
    "maturin>=1.11.4",
    "max",
    "numba",
    "numpy",
    "pandas",
    "tabulate>=0.9.0",
]
