[package]
name = "bench_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "bench_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27", features = ["extension-module"] }
rand = "0.8"
